version: '3'
services:
  web:
    build: .
    ports:
      - "9091:5000"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin